### ISSUE TITLE
MD5 is not secure

### ISSUE THREAD

**Issue by KeinR** [TheJeme/kupla#1]
Sorry, I just happened to stumble upon this, but I noticed that you claim that MD5 is secure in your project - namely [here](https://thejeme.github.io/Kupla-website/):

> Secure MD5 hash

> secure MD5 hash to generate password

This is misleading. MD5 is compromised and has been for a while.
- [wikipedia](https://en.wikipedia.org/wiki/MD5#Security)
- [article](https://www.md5online.org/blog/why-md5-is-not-safe/)
- [stack exchange](https://stackoverflow.com/questions/13756697/is-md5-still-considered-secure-for-single-use-authentications) <- note that this is from ~8 years ago, yet even then it was considered insecure

**Comment by thejeme** [comment]
I fixed misleading info with MD5 in my project.
